import './components/font-loader.js'
import './components/row.js'
import './components/logo.js'
import './components/menu.js'
import './components/hero.js'
import './components/category-filter.js'
import './components/gallery.js'
import './components/icons-list.js'
