import './components/font-loader.js'
import './components/row.js'
import './components/logo.js'
import './components/menu.js'
import './components/hero.js'
import './components/category-filter.js'
// import './components/gallery.js'
import './components/icons-list.js'
import './components/product-gallery.js'
import './components/notification.js'
import './components/add-button.js'
import './components/cart.js'
import './components/plus-minus-button.js'
import './components/product.js'
import './components/about.js'
